### ISSUE TITLE
Schedule?

### ISSUE THREAD

**Issue by richelbilderbeek** [NBISweden/Training-Tech-shorts#33]
Hi @mahesh-panchal, 

I enjoy this initiative, thanks for leading it! I do miss a schedule that shows what is taught by whom on which date.

Will the schedule of the Tech shorts be posted on the README of this repo as well? If not, where will it be?

Keep up the good work and cheers, Richel

**Comment by mahesh-panchal** [comment]
This is a good idea. I'll add one.

**Comment by mahesh-panchal** [comment]
Added with #889a302
