### ISSUE TITLE
Lesson: Quarto

### ISSUE THREAD

**Issue by mahesh-panchal** [NBISweden/Training-Tech-shorts#5]
- What is Quarto
- Code vs static text
- Basics of different output formats
  - Article/Report
  - Slides
  - Website
- Running in an environment. 
- Reading in data.

**Comment by Estel-Kitsune** [comment]
Hello! Can we get the "table of contents" and the assignees/reviewers here (as in the previous issues for Git and github collab)?

**Comment by mahesh-panchal** [comment]
Per put the assignees directly in the markdown of the branch. You'll see your section when you make a branch off his. 
Do you think it's better here? I found it more work seeing who was assigned to what when it was listed here. 

What I did was update my fork of the repository. Opened it in Gitpod.
```
git checkout upstream/quarto-intro
git checkout -b quarto-intro-computations # make new branch from upstream branch
git add ... # the normal workflow
```

**Comment by Estel-Kitsune** [comment]
No, it's fine in the doc in the branch! I was just looking here because that's where it was for the previous lesson :-)
